from time import sleep

def run(robot):
    robot.drivetrain.stop()
    sleep(1)

    robot.drivetrain.robotCentric(0, 1, 0)
    robot.drivetrain.telemetry.info("forward")
    sleep(1)
    robot.drivetrain.stop()
    sleep(0.5)
    robot.drivetrain.robotCentric(0, -1, 0)
    robot.drivetrain.telemetry.info("backward")
    sleep(2)
    robot.drivetrain.stop()
    sleep(0.5)
    robot.drivetrain.robotCentric(0, 1, 0)
    robot.drivetrain.telemetry.info("forward")
    sleep(1)

    robot.drivetrain.stop()
    sleep(1)

    robot.drivetrain.robotCentric(-1, 0, 0)
    robot.drivetrain.telemetry.info("left")
    sleep(1)
    robot.drivetrain.stop()
    sleep(0.5)
    robot.drivetrain.robotCentric(1, 0, 0)
    robot.drivetrain.telemetry.info("right")
    sleep(2)
    robot.drivetrain.stop()
    sleep(0.5)
    robot.drivetrain.robotCentric(-1, 0, 0)
    robot.drivetrain.telemetry.info("left")
    sleep(1)

    robot.drivetrain.stop()
    sleep(1)

    robot.drivetrain.robotCentric(0, 0, 1)
    robot.drivetrain.telemetry.info("rotate right")
    sleep(2)
    robot.drivetrain.stop()
    sleep(0.5)
    robot.drivetrain.robotCentric(0, 0, -1)
    robot.drivetrain.telemetry.info("rotate left")
    sleep(2)